// Select the database to use.
use('shop-app');

// Insert a few documents into the sales collection.
db.getCollection('products').insertMany([
    { "category": "guitar", "type": "acoustic", "name": "Taylor 210ce", "price": 2500 },
    { "category": "guitar", "type": "classic", "name": "Thomann Classic Guitar S 4/4", "price": 800 },
    { "category": "guitar", "type": "electric", "name": "Gitara3", "price": 1200 },
    { "category": "guitar", "type": "acoustic", "name": "Fender CD-60S", "price": 1500 },
    { "category": "guitar", "type": "classic", "name": "Yamaha CG122MC", "price": 900 },
    { "category": "guitar", "type": "electric", "name": "Gibson Les Paul Standard", "price": 3000 },
    { "category": "key_instrument", "type": "keyboard", "name": "Korg Krome", "price": 2800 },
    { "category": "key_instrument", "type": "synthesizer", "name": "Roland Juno-60", "price": 1500 },
    { "category": "key_instrument", "type": "electric_piano", "name": "Yamaha CP88", "price": 2000 },
    { "category": "key_instrument", "type": "keyboard", "name": "Roland RD-2000", "price": 3200 },
    { "category": "key_instrument", "type": "synthesizer", "name": "Korg Minilogue XD", "price": 1100 },
    { "category": "key_instrument", "type": "electric_piano", "name": "Yamaha P-125", "price": 1800 },
    { "category": "sound_equipment", "type": "processors", "name": "TC Electronic Helix", "price": 1500 },
    { "category": "sound_equipment", "type": "amplifier", "name": "Marshall JCM800", "price": 2200 },
    { "category": "sound_equipment", "type": "microphone", "name": "AKG C414", "price": 1000 },
    { "category": "sound_equipment", "type": "amplifier", "name": "Marshall JVM410H", "price": 2500 },
    { "category": "sound_equipment", "type": "microphone", "name": "Shure SM58", "price": 150 },
    { "category": "sound_equipment", "type": "processors", "name": "Behringer X32", "price": 3000 },
    { "category": "guitar", "type": "acoustic", "name": "Taylor 110ce", "price": 2300 },
    { "category": "guitar", "type": "classic", "name": "Epiphone PR-150", "price": 500 },
    { "category": "guitar", "type": "electric", "name": "Fender Stratocaster", "price": 1400 },
    { "category": "guitar", "type": "acoustic", "name": "Martin D-28", "price": 3500 },
    { "category": "guitar", "type": "classic", "name": "Cordoba C5", "price": 700 },
    { "category": "guitar", "type": "electric", "name": "PRS Custom 24", "price": 2700 },
    { "category": "key_instrument", "type": "keyboard", "name": "Yamaha MX49", "price": 900 },
    { "category": "key_instrument", "type": "synthesizer", "name": "Moog Subsequent 37", "price": 1800 },
    { "category": "key_instrument", "type": "electric_piano", "name": "Kawai MP7", "price": 2100 },
    { "category": "key_instrument", "type": "keyboard", "name": "Casio Privia PX-160", "price": 600 },
    { "category": "key_instrument", "type": "synthesizer", "name": "Nord Stage 3", "price": 3200 },
    { "category": "key_instrument", "type": "electric_piano", "name": "Roland RD-88", "price": 1900 },
    { "category": "sound_equipment", "type": "processors", "name": "Line 6 Helix LT", "price": 1200 },
    { "category": "sound_equipment", "type": "amplifier", "name": "Vox AC30", "price": 1500 },
    { "category": "sound_equipment", "type": "microphone", "name": "Neumann U87", "price": 2500 },
    { "category": "sound_equipment", "type": "amplifier", "name": "Fender Twin Reverb", "price": 1800 },
    { "category": "sound_equipment", "type": "microphone", "name": "Audio-Technica AT2020", "price": 100 },
    { "category": "sound_equipment", "type": "processors", "name": "Boss GT-1000", "price": 1400 },
    { "category": "guitar", "type": "acoustic", "name": "Gibson J-45", "price": 3200 },
    { "category": "guitar", "type": "classic", "name": "Ibanez AEG12II", "price": 600 },
    { "category": "guitar", "type": "electric", "name": "Gretsch G2622 Streamliner", "price": 800 },
    { "category": "guitar", "type": "acoustic", "name": "Seagull S6 Original", "price": 900 },
    { "category": "guitar", "type": "classic", "name": "Alhambra 4P", "price": 1100 },
    { "category": "guitar", "type": "electric", "name": "Jackson Soloist SL2Q", "price": 1700 },
    { "category": "key_instrument", "type": "keyboard", "name": "Kurzweil Artis SE", "price": 2200 },
    { "category": "key_instrument", "type": "synthesizer", "name": "Arturia MicroBrute", "price": 400 },
    { "category": "key_instrument", "type": "electric_piano", "name": "Casio PX-770", "price": 800 },
    { "category": "key_instrument", "type": "keyboard", "name": "Nord Electro 6D", "price": 2300 },
    { "category": "key_instrument", "type": "synthesizer", "name": "Novation Bass Station II", "price": 350 },
    { "category": "key_instrument", "type": "electric_piano", "name": "Korg SV-2", "price": 1600 },
    { "category": "sound_equipment", "type": "processors", "name": "Eventide H9", "price": 600 },
    { "category": "sound_equipment", "type": "amplifier", "name": "Blackstar HT Club 40", "price": 900 },
    { "category": "sound_equipment", "type": "microphone", "name": "Sennheiser e835", "price": 120 },
    { "category": "sound_equipment", "type": "amplifier", "name": "Orange Rocker 32", "price": 1300 },
    { "category": "sound_equipment", "type": "microphone", "name": "Blue Yeti", "price": 130 },
    { "category": "sound_equipment", "type": "processors", "name": "Zoom G5n", "price": 350 },
    { "category": "guitar", "type": "acoustic", "name": "Epiphone DR-100", "price": 150 },
    { "category": "guitar", "type": "classic", "name": "Yamaha CGS103A", "price": 120 },
    { "category": "guitar", "type": "electric", "name": "Epiphone Les Paul Standard", "price": 400 },
    { "category": "guitar", "type": "acoustic", "name": "Washburn WD10SCE", "price": 300 },
    { "category": "guitar", "type": "classic", "name": "Fender CN-60S", "price": 220 },
    { "category": "guitar", "type": "electric", "name": "Squier Affinity Series Stratocaster", "price": 250 },
    { "category": "key_instrument", "type": "keyboard", "name": "Kawai ES110", "price": 700 },
    { "category": "key_instrument", "type": "synthesizer", "name": "Waldorf Blofeld", "price": 800 },
    { "category": "key_instrument", "type": "electric_piano", "name": "Yamaha YDP-144", "price": 1000 },
    { "category": "key_instrument", "type": "keyboard", "name": "Casio CT-X700", "price": 150 },
    { "category": "key_instrument", "type": "synthesizer", "name": "Arturia MiniLab MkII", "price": 100 },
]);
